In [2]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import plotly.express as px
import pickle

In [3]:
# Importing call data
with open('forecast_3-31-2024.pkl', 'rb') as fp:
    output_dict = pickle.load(fp)
    print('Predictions dictionary')
    print(output_dict)

Predictions dictionary
{'scores':          location        rmse
0             1.0    6.549491
1             5.0    3.527881
2             6.0    3.282335
3             7.0    3.343227
4             9.0    3.205772
..            ...         ...
78       BROOKLYN   40.909308
79      MANHATTAN   41.109343
80         QUEENS   23.026644
81  STATEN ISLAND    7.626596
82          total  106.772812

[83 rows x 2 columns], '1.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   7.000000    7.000000    7.000000        0
1     2018-01-01 01:00:00  14.000000   14.000000   14.000000        0
2     2018-01-01 02:00:00  21.000000   21.000000   21.000000        0
3     2018-01-01 03:00:00  16.000000   16.000000   16.000000        0
4     2018-01-01 04:00:00  11.000000   11.000000   11.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  17.586911   13.705417   21.947451        2
69282 2024-07-10 16:00:00  18.156196   13.940474   22.472225        2
69283 2024-07-10 17:00:00  17.829739   13.803392   22.034413        2
69284 2024-07-10 18:00:00  16.575469   12.363875   20.760062        2
69285 2024-07-10 19:00:00  14.703689   10.416860   18.695217        2

[69286 rows x 5 columns], '5.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   6.000000    6.000000    6.000000        0
1     2018-01-01 01:00:00  16.000000   16.000000   16.000000        0
2     2018-01-01 02:00:00  16.000000   16.000000   16.000000        0
3     2018-01-01 03:00:00   8.000000    8.000000    8.000000        0
4     2018-01-01 04:00:00   7.000000    7.000000    7.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  10.860031    7.838694   13.589602        2
69282 2024-07-10 16:00:00  11.159198    8.275727   14.113954        2
69283 2024-07-10 17:00:00  11.037312    8.282062   13.868358        2
69284 2024-07-10 18:00:00  10.659072    7.788209   13.609446        2
69285 2024-07-10 19:00:00  10.135234    7.175427   13.121068        2

[69286 rows x 5 columns], '6.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  10.000000   10.000000   10.000000        0
1     2018-01-01 01:00:00  23.000000   23.000000   23.000000        0
2     2018-01-01 02:00:00  29.000000   29.000000   29.000000        0
3     2018-01-01 03:00:00  12.000000   12.000000   12.000000        0
4     2018-01-01 04:00:00   9.000000    9.000000    9.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  11.596601    9.122059   14.155865        2
69282 2024-07-10 16:00:00  12.151108    9.552027   14.718663        2
69283 2024-07-10 17:00:00  12.005479    9.239844   14.615511        2
69284 2024-07-10 18:00:00  11.299249    8.787733   13.734857        2
69285 2024-07-10 19:00:00  10.396734    7.827851   13.101888        2

[69286 rows x 5 columns], '7.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  11.000000   11.000000   11.000000        0
1     2018-01-01 01:00:00  13.000000   13.000000   13.000000        0
2     2018-01-01 02:00:00  14.000000   14.000000   14.000000        0
3     2018-01-01 03:00:00  15.000000   15.000000   15.000000        0
4     2018-01-01 04:00:00   5.000000    5.000000    5.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  10.856306    8.102625   13.948690        2
69282 2024-07-10 16:00:00  11.514451    8.309371   14.357742        2
69283 2024-07-10 17:00:00  11.433188    8.602940   14.524761        2
69284 2024-07-10 18:00:00  10.834427    8.014559   13.755168        2
69285 2024-07-10 19:00:00  10.040842    7.317122   12.896983        2

[69286 rows x 5 columns], '9.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  17.000000   17.000000   17.000000        0
1     2018-01-01 01:00:00  24.000000   24.000000   24.000000        0
2     2018-01-01 02:00:00  20.000000   20.000000   20.000000        0
3     2018-01-01 03:00:00  14.000000   14.000000   14.000000        0
4     2018-01-01 04:00:00   8.000000    8.000000    8.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  10.057607    7.388546   12.837094        2
69282 2024-07-10 16:00:00  10.875298    8.324294   13.498421        2
69283 2024-07-10 17:00:00  11.388353    8.780791   14.190052        2
69284 2024-07-10 18:00:00  11.375639    8.823626   13.997115        2
69285 2024-07-10 19:00:00  10.811989    8.340247   13.340176        2

[69286 rows x 5 columns], '10.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   9.000000    9.000000    9.000000        0
1     2018-01-01 01:00:00  18.000000   18.000000   18.000000        0
2     2018-01-01 02:00:00  13.000000   13.000000   13.000000        0
3     2018-01-01 03:00:00  18.000000   18.000000   18.000000        0
4     2018-01-01 04:00:00   9.000000    9.000000    9.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  11.611138    8.696903   14.375954        2
69282 2024-07-10 16:00:00  12.812058   10.049810   15.523647        2
69283 2024-07-10 17:00:00  13.038630   10.258391   15.567620        2
69284 2024-07-10 18:00:00  12.255443    9.480890   15.077305        2
69285 2024-07-10 19:00:00  11.099403    8.128072   13.773916        2

[69286 rows x 5 columns], '13.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  13.000000   13.000000   13.000000        0
1     2018-01-01 01:00:00  24.000000   24.000000   24.000000        0
2     2018-01-01 02:00:00  18.000000   18.000000   18.000000        0
3     2018-01-01 03:00:00  14.000000   14.000000   14.000000        0
4     2018-01-01 04:00:00  10.000000   10.000000   10.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  18.499318   14.339534   22.276626        2
69282 2024-07-10 16:00:00  18.843328   14.988941   22.633823        2
69283 2024-07-10 17:00:00  18.346481   14.209412   22.441629        2
69284 2024-07-10 18:00:00  17.526657   13.423449   21.233819        2
69285 2024-07-10 19:00:00  16.911448   13.114544   21.205064        2

[69286 rows x 5 columns], '14.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  27.000000   27.000000   27.000000        0
1     2018-01-01 01:00:00  33.000000   33.000000   33.000000        0
2     2018-01-01 02:00:00  35.000000   35.000000   35.000000        0
3     2018-01-01 03:00:00  28.000000   28.000000   28.000000        0
4     2018-01-01 04:00:00  18.000000   18.000000   18.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  36.463223   30.855990   42.564839        2
69282 2024-07-10 16:00:00  38.619704   32.884480   44.430571        2
69283 2024-07-10 17:00:00  39.022904   33.300226   45.109190        2
69284 2024-07-10 18:00:00  38.064641   32.098679   43.589194        2
69285 2024-07-10 19:00:00  36.334049   30.499778   42.462405        2

[69286 rows x 5 columns], '17.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   5.000000    5.000000    5.000000        0
1     2018-01-01 01:00:00  13.000000   13.000000   13.000000        0
2     2018-01-01 02:00:00  14.000000   14.000000   14.000000        0
3     2018-01-01 03:00:00  13.000000   13.000000   13.000000        0
4     2018-01-01 04:00:00   9.000000    9.000000    9.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  11.490254    8.670569   14.182744        2
69282 2024-07-10 16:00:00  11.864773    9.075103   14.558207        2
69283 2024-07-10 17:00:00  11.835454    8.919851   14.824809        2
69284 2024-07-10 18:00:00  11.485405    8.790918   14.108323        2
69285 2024-07-10 19:00:00  10.948212    8.232633   13.923399        2

[69286 rows x 5 columns], '18.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  20.000000   20.000000   20.000000        0
1     2018-01-01 01:00:00  27.000000   27.000000   27.000000        0
2     2018-01-01 02:00:00  32.000000   32.000000   32.000000        0
3     2018-01-01 03:00:00  26.000000   26.000000   26.000000        0
4     2018-01-01 04:00:00  20.000000   20.000000   20.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  31.131383   26.868525   35.318212        2
69282 2024-07-10 16:00:00  32.463119   28.411978   36.833051        2
69283 2024-07-10 17:00:00  32.570595   28.431592   36.753747        2
69284 2024-07-10 18:00:00  31.890190   27.678351   36.338895        2
69285 2024-07-10 19:00:00  30.941541   26.690261   35.325335        2

[69286 rows x 5 columns], '19.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  11.000000   11.000000   11.000000        0
1     2018-01-01 01:00:00  16.000000   16.000000   16.000000        0
2     2018-01-01 02:00:00  12.000000   12.000000   12.000000        0
3     2018-01-01 03:00:00   7.000000    7.000000    7.000000        0
4     2018-01-01 04:00:00   6.000000    6.000000    6.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  15.065838   11.178484   18.916837        2
69282 2024-07-10 16:00:00  15.101423   11.264800   19.049335        2
69283 2024-07-10 17:00:00  14.589731   10.832612   18.343715        2
69284 2024-07-10 18:00:00  13.710394    9.971307   17.507110        2
69285 2024-07-10 19:00:00  12.548670    8.643587   16.120679        2

[69286 rows x 5 columns], '20.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   6.000000    6.000000    6.000000        0
1     2018-01-01 01:00:00   6.000000    6.000000    6.000000        0
2     2018-01-01 02:00:00   7.000000    7.000000    7.000000        0
3     2018-01-01 03:00:00   4.000000    4.000000    4.000000        0
4     2018-01-01 04:00:00   8.000000    8.000000    8.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  10.862378    8.426287   13.387293        2
69282 2024-07-10 16:00:00  11.111656    8.745727   13.586967        2
69283 2024-07-10 17:00:00  10.675824    8.256462   13.089243        2
69284 2024-07-10 18:00:00   9.809815    7.389351   12.306185        2
69285 2024-07-10 19:00:00   8.923515    6.492755   11.332996        2

[69286 rows x 5 columns], '22.0':                        ds      yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  0.000000    0.000000    0.000000        0
1     2018-01-01 01:00:00  0.000000    0.000000    0.000000        0
2     2018-01-01 02:00:00  2.000000    2.000000    2.000000        0
3     2018-01-01 03:00:00  0.000000    0.000000    0.000000        0
4     2018-01-01 04:00:00  0.000000    0.000000    0.000000        0
...                   ...       ...         ...         ...      ...
69281 2024-07-10 15:00:00  2.771129    1.478965    4.142685        2
69282 2024-07-10 16:00:00  2.881367    1.504352    4.217912        2
69283 2024-07-10 17:00:00  2.965663    1.574665    4.423600        2
69284 2024-07-10 18:00:00  2.977628    1.578750    4.409929        2
69285 2024-07-10 19:00:00  2.767596    1.478797    4.302151        2

[69286 rows x 5 columns], '23.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   9.000000    9.000000    9.000000        0
1     2018-01-01 01:00:00  10.000000   10.000000   10.000000        0
2     2018-01-01 02:00:00  14.000000   14.000000   14.000000        0
3     2018-01-01 03:00:00   6.000000    6.000000    6.000000        0
4     2018-01-01 04:00:00   7.000000    7.000000    7.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  13.617997    9.979332   17.187079        2
69282 2024-07-10 16:00:00  14.851699   11.459238   18.301782        2
69283 2024-07-10 17:00:00  16.215400   12.818943   19.838048        2
69284 2024-07-10 18:00:00  16.915644   13.585700   20.409492        2
69285 2024-07-10 19:00:00  16.239146   12.888592   19.818254        2

[69286 rows x 5 columns], '24.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   8.000000    8.000000    8.000000        0
1     2018-01-01 01:00:00  15.000000   15.000000   15.000000        0
2     2018-01-01 02:00:00  10.000000   10.000000   10.000000        0
3     2018-01-01 03:00:00  12.000000   12.000000   12.000000        0
4     2018-01-01 04:00:00   9.000000    9.000000    9.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  16.339780   13.115610   19.476974        2
69282 2024-07-10 16:00:00  17.599397   14.100596   21.027343        2
69283 2024-07-10 17:00:00  18.196449   14.812081   21.630937        2
69284 2024-07-10 18:00:00  17.669109   14.544249   21.253999        2
69285 2024-07-10 19:00:00  16.282355   12.924351   19.680750        2

[69286 rows x 5 columns], '25.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   7.000000    7.000000    7.000000        0
1     2018-01-01 01:00:00   9.000000    9.000000    9.000000        0
2     2018-01-01 02:00:00  14.000000   14.000000   14.000000        0
3     2018-01-01 03:00:00   7.000000    7.000000    7.000000        0
4     2018-01-01 04:00:00  10.000000   10.000000   10.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  17.462805   13.807710   20.899037        2
69282 2024-07-10 16:00:00  18.189341   14.599507   21.536865        2
69283 2024-07-10 17:00:00  18.994014   15.661110   22.548868        2
69284 2024-07-10 18:00:00  19.497819   16.080275   23.057955        2
69285 2024-07-10 19:00:00  18.990731   15.178886   22.080868        2

[69286 rows x 5 columns], '26.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   5.000000    5.000000    5.000000        0
1     2018-01-01 01:00:00   8.000000    8.000000    8.000000        0
2     2018-01-01 02:00:00  10.000000   10.000000   10.000000        0
3     2018-01-01 03:00:00   1.000000    1.000000    1.000000        0
4     2018-01-01 04:00:00   8.000000    8.000000    8.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  13.667872   10.382999   16.863471        2
69282 2024-07-10 16:00:00  14.243051   10.775225   17.419150        2
69283 2024-07-10 17:00:00  14.585262   11.285761   18.278180        2
69284 2024-07-10 18:00:00  14.486953   11.623097   17.855991        2
69285 2024-07-10 19:00:00  13.795406   10.529274   17.094155        2

[69286 rows x 5 columns], '28.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  11.000000   11.000000   11.000000        0
1     2018-01-01 01:00:00  11.000000   11.000000   11.000000        0
2     2018-01-01 02:00:00  13.000000   13.000000   13.000000        0
3     2018-01-01 03:00:00  10.000000   10.000000   10.000000        0
4     2018-01-01 04:00:00   4.000000    4.000000    4.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  14.518952   11.824333   17.432941        2
69282 2024-07-10 16:00:00  15.018934   12.126165   17.771575        2
69283 2024-07-10 17:00:00  15.155386   12.114115   17.873438        2
69284 2024-07-10 18:00:00  14.766939   11.920286   17.354841        2
69285 2024-07-10 19:00:00  13.770167   10.899717   16.517193        2

[69286 rows x 5 columns], '30.0':                        ds      yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  2.000000    2.000000    2.000000        0
1     2018-01-01 01:00:00  5.000000    5.000000    5.000000        0
2     2018-01-01 02:00:00  8.000000    8.000000    8.000000        0
3     2018-01-01 03:00:00  5.000000    5.000000    5.000000        0
4     2018-01-01 04:00:00  6.000000    6.000000    6.000000        0
...                   ...       ...         ...         ...      ...
69281 2024-07-10 15:00:00  8.666049    5.812361   11.272646        2
69282 2024-07-10 16:00:00  8.495813    5.825512   11.088670        2
69283 2024-07-10 17:00:00  8.234968    5.442933   10.788203        2
69284 2024-07-10 18:00:00  8.118666    5.373454   10.630818        2
69285 2024-07-10 19:00:00  8.064389    5.199381   10.732415        2

[69286 rows x 5 columns], '32.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   9.000000    9.000000    9.000000        0
1     2018-01-01 01:00:00  14.000000   14.000000   14.000000        0
2     2018-01-01 02:00:00   7.000000    7.000000    7.000000        0
3     2018-01-01 03:00:00   9.000000    9.000000    9.000000        0
4     2018-01-01 04:00:00  14.000000   14.000000   14.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  17.707290   14.483798   20.928731        2
69282 2024-07-10 16:00:00  18.499909   15.272639   21.681787        2
69283 2024-07-10 17:00:00  19.665754   16.190113   22.819477        2
69284 2024-07-10 18:00:00  20.767945   17.373739   24.037884        2
69285 2024-07-10 19:00:00  21.103770   17.773438   24.591294        2

[69286 rows x 5 columns], '33.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   9.000000    9.000000    9.000000        0
1     2018-01-01 01:00:00   7.000000    7.000000    7.000000        0
2     2018-01-01 02:00:00  13.000000   13.000000   13.000000        0
3     2018-01-01 03:00:00  13.000000   13.000000   13.000000        0
4     2018-01-01 04:00:00  10.000000   10.000000   10.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  11.851724    8.610899   15.040934        2
69282 2024-07-10 16:00:00  12.708888    9.464042   15.856039        2
69283 2024-07-10 17:00:00  13.061177    9.636159   16.025298        2
69284 2024-07-10 18:00:00  12.797039    9.471883   16.393330        2
69285 2024-07-10 19:00:00  12.055468    8.770208   15.420745        2

[69286 rows x 5 columns], '34.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00   7.000000    7.000000    7.000000        0
1     2018-01-01 01:00:00  13.000000   13.000000   13.000000        0
2     2018-01-01 02:00:00  14.000000   14.000000   14.000000        0
3     2018-01-01 03:00:00  16.000000   16.000000   16.000000        0
4     2018-01-01 04:00:00  10.000000   10.000000   10.000000        0
...                   ...        ...         ...         ...      ...
69281 2024-07-10 15:00:00  11.440287    7.902134   15.307526        2
69282 2024-07-10 16:00:00  12.627989    9.400506   16.526798        2
69283 2024-07-10 17:00:00  13.318542   10.011459   16.726294        2
69284 2024-07-10 18:00:00  13.261985    9.892061   16.679955        2
69285 2024-07-10 19:00:00  12.653923    9.458354   16.228386        2

[69286 rows x 5 columns], '40.0':                        ds       yhat  yhat_lower  yhat_upper  quality
0     2018-01-01 00:00:00  14.000000   14.000000   14.000000        0
1     2018-01-01 01:00:00  30.000000   30.000000   30.000000        0
2     2018-01-01 02:00:00  26.000000   26.000000   26.000000        0
3     2018-01-01 03:00:00  19.000000   19.000000   19.000000        0

Shape files can be found for download at the links below:
* [Borough Boundaries](https://data.cityofnewyork.us/City-Government/Borough-Boundaries/tqmj-j8zm)
* [Precinct Boundaries](https://data.cityofnewyork.us/Public-Safety/Police-Precincts/78dh-3ptz)

In [ ]:
# Importing Shapefile
nyc_precincts_gdf = gpd.read_file(r"C:\Users\cmphi\Documents\BrainStation\Capstone_911_working\misc\geo_export_2a60d339-10a3-49f4-919d-1112cd8c952c.shp")

In [5]:
# Aggregate calls by precinct
precinct_calls = {precinct: df['yhat'].sum() for precinct, df in data.items() if precinct.isdigit()}

# Convert to DataFrame
precinct_calls_df = pd.DataFrame(list(precinct_calls.items()), columns=['precinct', 'total_calls'])

# Merge with GeoDataFrame
nyc_precincts_gdf['precinct'] = nyc_precincts_gdf['precinct'].astype(str)
precincts_merged = nyc_precincts_gdf.merge(precinct_calls_df, left_on='precinct', right_on='precinct')

# Plot heat map for precincts
precincts_merged.plot(column='total_calls', cmap='OrRd', legend=True)
plt.title('Heat Map of Calls by Precinct')
plt.show()

# Aggregate calls by borough
borough_calls = {borough: sum(data[precinct]['yhat'].sum() for precinct in data if precinct in data[borough]) for borough in ['BRONX', 'BROOKLYN', 'MANHATTAN', 'QUEENS', 'STATEN ISLAND']}

# Convert to DataFrame
borough_calls_df = pd.DataFrame(list(borough_calls.items()), columns=['borough', 'total_calls'])

# Merge with GeoDataFrame
boroughs_merged = nyc_precincts_gdf.dissolve(by='borough')
boroughs_merged = boroughs_merged.merge(borough_calls_df, left_on='borough', right_on='borough')

# Plot heat map for boroughs
boroughs_merged.plot(column='total_calls', cmap='OrRd', legend=True)
plt.title('Heat Map of Calls by Borough')
plt.show()

NameError: name 'data' is not defined

In [ ]:
fig = px.density_mapbox(