# API Dataset
This notebook will focus on creating the database that will be used through this project. Here I will be using the NYC open data api to pull infromation from there website and add it to the database. I Need to pull from two seperate but very similar data sets, one with the inforamtion year to data (that is 01/01/2024 -> 03/31/2024). I will then combine that with the historic dataset that contains the same information back to ~2018.

In [34]:
import pandas as pd
from sodapy import Socrata

In [38]:
client = Socrata('data.cityofnewyork.us',
                 '2zEO885pCsTLIk5R1E9lnRTm6',
                 username="Cmphillipps73@gmail.com",
                 password="Roxz124!")


results = client.get("d6zx-ckhd", limit=100000, offset=0)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)
display(results_df.head())
print(len(results_df))

,cad_evnt_id,create_date,incident_date,incident_time,nypd_pct_cd,boro_nm,patrl_boro_nm,geo_cd_x,geo_cd_y,radio_code,...,closng_ts,latitude,longitude,location,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_sbqj_enih,:@computed_region_92fq_4b7q,arrivd_ts
0,55489198,2019-02-17T00:00:00.000,2019-02-17T00:00:00.000,19:21:38,42,BRONX,PATROL BORO BRONX,1010158,242491,52D6,...,2019-02-17T20:12:34.000,40.832227424000052,-73.906379769999944,"{'type': 'Point', 'coordinates': [-73.90637976...",10934,34,5,25,42,NaN
1,55538602,2019-02-19T00:00:00.000,2019-02-19T00:00:00.000,16:57:09,100,QUEENS,PATROL BORO QUEENS SOUTH,1037138,154271,31R,...,2019-02-19T17:38:19.000,40.58996484000005,-73.809577510999986,"{'type': 'Point', 'coordinates': [-73.80957751...",20531,51,3,58,47,2019-02-19T16:58:36.000
2,56336511,2019-03-19T00:00:00.000,2019-03-19T00:00:00.000,22:10:23,46,BRONX,PATROL BORO BRONX,1007522,247458,10Y3,...,2019-03-19T22:53:55.000,40.845867730000066,-73.915888032999987,"{'type': 'Point', 'coordinates': [-73.91588803...",10930,6,5,29,29,NaN
3,56122147,2019-03-12T00:00:00.000,2019-03-12T00:00:00.000,16:16:12,44,BRONX,PATROL BORO BRONX,1006195,240321,68Q1,...,2019-03-12T16:55:08.000,40.826282132000074,-73.920707637999953,"{'type': 'Point', 'coordinates': [-73.92070763...",10929,50,5,27,42,NaN
4,59509400,2019-07-03T00:00:00.000,2019-07-03T00:00:00.000,19:36:20,41,BRONX,PATROL BORO BRONX,1011632,238408,54S1,...,2019-07-03T20:01:53.000,40.821016310000061,-73.901069959999973,"{'type': 'Point', 'coordinates': [-73.90106995...",10937,34,5,25,43,2019-07-03T19:53:12.000

100000

Here the bulk of the heavy lifting is done. For the sake of sprint 1 I will leave it hear and focus on EDA with just the year to date data. This is giving some issues that will take a bit to work out.<br><br>
The entry point for pulling data seems to be chaning, that is to say when running the code above the first entry is never the same even without changing the offest. This will be difficlut to prove that I have pulled the entire dataset as ever .get() will start from a different seciton. I believe it is just that I am missing something, but ideal I will create a loop and just loop through the .get() function to pull the information and increase the offset at every loop untill all the information has been put into the panda dataframe. I will then need to create another loop just like the one above but for the historic data base/year to date and concat the two together. From that point I will save it as a csv so this setp only needs to be run one and input the full data set into the Basic EDA notebook.